#!/bin/bash
# =============================================================================
# Drowsiness Detection - Quick Start Scripts
# =============================================================================

echo "=========================================="
echo "🚗 DETECCIÓN DE SOMNOLENCIA - STANDALONE"
echo "=========================================="
echo ""
echo "Este directorio contiene scripts para ejecutar la detección"
echo "de somnolencia SIN necesidad de abrir un navegador."
echo ""
echo "SCRIPTS DISPONIBLES:"
echo "--------------------"
echo ""
echo "1. standalone_detector.py"
echo "   Ejecuta la detección directamente con OpenCV."
echo "   "
echo "   Uso:"
echo "     python standalone_detector.py --viaje_id 123"
echo "     python standalone_detector.py --viaje_id 123 --camera 0"
echo "     python standalone_detector.py --viaje_id 123 --headless"
echo "     python standalone_detector.py --list-cameras"
echo ""
echo "2. auto_start.py"
echo "   Busca/crea un viaje automáticamente e inicia la detección."
echo "   Ideal para iniciar en el arranque del sistema."
echo "   "
echo "   Uso:"
echo "     python auto_start.py --conductor_id 1"
echo "     python auto_start.py --conductor_id 1 --vehiculo_id 2"
echo "     python auto_start.py --conductor_id 1 --wait --headless"
echo ""
echo "3. Servicio systemd (drowsiness-detector.service)"
echo "   Para ejecutar automáticamente al iniciar el sistema:"
echo "   "
echo "   # Edita el archivo para configurar tu conductor_id"
echo "   nano drowsiness-detector.service"
echo "   "
echo "   # Copia el servicio"
echo "   sudo cp drowsiness-detector.service /etc/systemd/system/"
echo "   "
echo "   # Habilita e inicia"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable drowsiness-detector"
echo "   sudo systemctl start drowsiness-detector"
echo "   "
echo "   # Ver logs"
echo "   journalctl -u drowsiness-detector -f"
echo ""
echo "=========================================="
echo "EJEMPLO RÁPIDO:"
echo "=========================================="
echo ""
echo "# Activar entorno virtual"
echo "source env/bin/activate"
echo ""
echo "# Ver cámaras disponibles"
echo "python standalone_detector.py --list-cameras"
echo ""
echo "# Iniciar detección con viaje existente"
echo "python standalone_detector.py --viaje_id 123"
echo ""
echo "# O auto-iniciar creando viaje"
echo "python auto_start.py --conductor_id 1"
echo ""
